import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);
  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();
  // تابع مساعد للوصول إلى الترجمة من الـ Widgets
  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  // خريطة النصوص المترجمة
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'welcome': 'Welcome to EduMind',
      'magic_start': 'Magic Start',
      'change_language': 'Change Language',
      'student_profile': 'Student Profile',
      'level 3': 'Level 3',
      // home (AI-game learning path)
      'level_label': 'Level',
      'points_label': 'points',
      'create_game': 'Create a game',
      'create_first_game': 'Create your first game!',
      'tap_to_play': 'Tap to play!',
      'my_games': 'My games',
      'demo_games': 'Demo games',
      'demo_games_short': 'Demos',
      'demo_games_sub': 'Bundled sample games you can play offline.',
      'best_score': 'Best',
      'plays': 'plays',
      'play': 'Play',
      'not_now': 'Not now',
      'lets_play': "Let's play!",
      'stage_intro_body':
          'Hudhud and Nahla are ready to help you with "{title}" and collect the sweetest honey of knowledge! Ready for the challenge?',
      'welcome_to': 'Welcome to {title}',
      'offline_create_hint':
          'Connect to a server to create new games. You can still replay saved ones offline.',
      // settings
      'settings': 'Settings',
      'server_address': 'Server address',
      'test_connection': 'Test connection',
      'connection_ok': 'Connected! Server is healthy.',
      'connection_fail': 'Could not reach the server.',
      'change_theme': 'Change theme',
      'language': 'Language',
      'privacy_note':
          'Data minimization: nickname only — no email, no analytics.',
      'nav_home': 'Home',
      'nav_profile': 'Profile',
      'nav_about': 'About',
      'nav_settings': 'Settings',
      'nav_learn': 'Journeys',
      // middle-school shell (grades 7-9)
      'nav_start': 'Home',
      'nav_journey': 'My Journey',
      'nav_tutor': 'My Tutor',
      'nav_me': 'Me',
      'journey_title': 'My Journey',
      'journey_subtitle':
          'Your real Grade 7 map: what you completed, where you are, and what unlocks next.',
      'journey_pick_sub':
          'Pick your path: each one is a big idea from your curriculum, told through real lessons.',
      'journey_pick_path': 'Pick your path!',
      'journey_locked': 'Locked',
      'path_ready_progress': '{n} of {m} ready',
      // honest grade gating (grades whose curriculum is not authored yet)
      'grade_word_7': 'Grade 7',
      'grade_word_8': 'Grade 8',
      'grade_word_9': 'Grade 9',
      'grade_soon_title': 'The {g} curriculum is being prepared',
      'grade_soon_body':
          "We are building your grade's lessons with the same care we gave Grade 7 — and we will never show you content that is not for your grade.",
      'grade_soon_can': 'What you can do now',
      'grade_soon_ask': 'Ask your tutor about any lesson',
      'start_greeting': 'Welcome back,',
      'start_subtitle': 'One clear step at a time — pick up where you left off.',
      'start_continue': 'CONTINUE YOUR JOURNEY',
      'start_begin': 'START YOUR JOURNEY',
      'start_continue_cta': 'Continue learning',
      'start_begin_cta': 'Start learning',
      'start_all_done_title': 'You completed every open experience!',
      'start_all_done_body':
          'New experiences are on the way. Meanwhile, replay any experience from your journey or explore an idea with your tutor.',
      'start_open_journey': 'Open my journey',
      'start_ask_title': 'Ask your tutor',
      'start_ask_sub': 'A question about anything — get a hint, not just an answer.',
      'start_now_label': 'Your learning moment now',
      'start_begin_exp': 'Start the experience',
      'start_resume_exp': 'Continue the experience',
      'start_explore_next': 'Explore the next concept',
      'start_exp_position': 'Experience {n} of {m} on this path',
      'start_resume_step': 'You stopped at step {n} of {m}',
      'journey_here': 'You are here',
      'me_title': 'Me',
      'me_stage_middle': 'Middle school',
      'me_experiences_done': 'experiences completed',
      'me_paths_done': 'paths completed',
      'me_advanced': 'Advanced',
      // context lens (middle school)
      'ctx_sheet_title': 'Your learning lens',
      'ctx_sheet_sub':
          'Pick the world your examples come from. It changes the story around an idea — never the idea, its difficulty, or your progress.',
      'ctx_chip_label': 'My lens',
      'ctx_chip_pick': 'Pick a learning lens',
      'ctx_none': 'No lens',
      'ctx_market': 'Market & trade',
      'ctx_building': 'Building & construction',
      'ctx_water_energy': 'Water & energy',
      'ctx_roads_transport': 'Roads & transport',
      'ctx_technology': 'Technology',
      // learning engine (features/learn)
      'learn_title': 'Learning journeys',
      'learn_subtitle':
          'Real situations from your city and neighborhood — you explore, decide, and discover the idea yourself.',
      'learn_grade': 'Grade',
      'learn_experiences': 'experiences',
      'learn_start': 'Start',
      'learn_replay': 'Replay',
      'learn_soon': 'Coming soon',
      'learn_continue': 'Continue',
      'learn_finish': 'Finish',
      'learn_done_title': 'Mission accomplished!',
      'learn_done_body': 'You made the decisions and discovered the idea in',
      'learn_back_to_path': 'Back to the journey',
      'learn_need_help': 'Need help?',
      // check step (تحقق من الفهم)
      'learn_check_item': 'Question {n} of {m}',
      'learn_check_next': 'Next',
      'learn_check_score': 'You answered {c} of {m} correctly',
      'learn_check_review': 'Review the idea with your tutor',
      // Ask OpenMind (tutor)
      'nav_ask': 'Ask',
      'tutor_title': 'Ask OpenMind',
      'tutor_subtitle':
          'A question about any subject — I will help you think it through, not just hand you the answer.',
      'tutor_welcome':
          'Hi! Ask me about math, science, Arabic, English, or anything you are learning. I will guide you step by step.',
      'tutor_input_hint': 'Write your question…',
      'tutor_thinking': 'Thinking…',
      'tutor_offline': 'Connect to a server first (Settings) so I can answer your questions.',
      'tutor_error': 'Something went wrong — try again in a moment.',
      'tutor_rate_limited': 'That is a lot of questions this hour! Take a short break and come back.',
      'tutor_try_again': 'Now try it yourself!',
      'tutor_help_title': 'OpenMind help',
      'tutor_type_explanation': 'Explanation',
      'tutor_type_hint': 'Hint',
      'tutor_type_question': 'Question',
      'tutor_type_encouragement': 'Keep going',
      'tutor_type_correction': 'Correction',
      'tutor_type_next_step': 'Next step',
      // tutor quick actions (middle school)
      'qa_simpler': 'Explain it more simply',
      'qa_example_ctx': 'Give me an example from my context',
      'qa_ask_me': 'Ask me a question that helps me understand',
      'qa_try_again': 'Let me try again',
      'qa_hint_only': 'Give me a hint, not the solution',
      // tutor interactive blocks (Ask → See → Try)
      'tutor_new_chat': 'New conversation',
      'blk_check': 'Check',
      'blk_your_value': 'Your value',
      'blk_correct': 'Correct! Well done',
      'blk_partial': 'Close — look at the marked spots',
      'blk_incorrect': 'Not right yet — your tutor will pick it up from here',
      'blk_sent': 'Your result went to your tutor',
      'blk_answered': 'You completed this activity — its result is with your tutor',
      'blk_item_of': 'Item {n} of {m}',
      'blk_pair_of': 'Matched {n} of {m} pairs',
      'ir_numberline': 'I placed the marker at {v} (target {t})',
      'ir_order': 'My order: {list}',
      'ir_sort': 'I sorted {c} of {m} correctly',
      'ir_match': 'I matched all {m} pairs with {c} wrong tries',
      // onboarding (5-step learner flow)
      'onb_title': 'Welcome to OpenMind',
      'onb_subtitle': "Let's start a learning journey that fits you",
      'onb_cta': 'Start',
      'onb_next': 'Next',
      'onb_back': 'Back',
      'onb_step_of': 'Step {n} of {m}',
      'onb_name_title': "What's your name?",
      'onb_name_sub': 'So we know what to call you',
      'onb_name_hint': 'Type your name here',
      'onb_stage_title': 'What stage are you in?',
      'onb_stage_sub': 'Pick your stage and your grade',
      'onb_stage_primary': 'Primary',
      'onb_stage_middle': 'Middle school',
      'onb_grade_sem': 'Grade {g}',
      'onb_g1': 'Grade 1',
      'onb_g2': 'Grade 2',
      'onb_g3': 'Grade 3',
      'onb_g4': 'Grade 4',
      'onb_g5': 'Grade 5',
      'onb_g6': 'Grade 6',
      'onb_g7': 'Grade 7',
      'onb_g8': 'Grade 8',
      'onb_g9': 'Grade 9',
      'onb_interests_title': 'What things do you love?',
      'onb_interests_sub': 'Pick two',
      'onb_int_science': 'Science & inventions',
      'onb_int_tech': 'Tech & future',
      'onb_int_sport': 'Sports & motion',
      'onb_int_art': 'Drawing & design',
      'onb_int_stories': 'Stories & history',
      'onb_int_nature': 'Nature & environment',
      'onb_count_of': '{n} of 2',
      'onb_style_title': 'How would you like to start?',
      'onb_style_sub': 'Pick the way that feels closest to you',
      'onb_style_step': 'Explain it to me step by step',
      'onb_style_try': 'Let me try it myself',
      'onb_style_story': 'A story and an adventure',
      'onb_style_real': 'From a real situation',
      'onb_accent_title': 'Pick the color of your space',
      'onb_color_blue': 'Blue',
      'onb_color_green': 'Green',
      'onb_color_yellow': 'Yellow',
      'onb_color_teal': 'Teal',
      'onb_color_coral': 'Coral',
      'onb_color_orange': 'Orange',
      'onb_finish_cta': 'Start my journey',
      'onb_done_hi': 'Welcome, {name}!',
      'onb_done_sub': 'Your journey is ready',
      // profile setup
      'ps_appbar': 'Set up your experience',
      'ps_name_q': "What's your name?",
      'ps_name_hint': 'Your name',
      'ps_gender_q': 'You are',
      'ps_male': 'Boy',
      'ps_female': 'Girl',
      'ps_class_q': 'Which grade are you in?',
      'ps_class_hint': 'Choose your grade',
      'ps_interests_q': 'What do you love? (pick up to 2)',
      'ps_style_q': 'How do you like to learn?',
      'ps_continue': 'Continue',
      'ps_max_interests':
          'You can pick just two interests for smart personalization!',
      'ps_sub': 'Simple choices that make EduMind closer to you',
      'ps_basic': 'Basic info',
      'ps_basic_sub': 'Name, gender and academic grade',
      'ps_name_label': 'Your name',
      'ps_name_hint2': 'Type your name here ...',
      'ps_class_label': 'Your grade',
      'ps_class_hint2': 'Choose your current grade',
      'ps_interests_sec': 'Interests',
      'ps_interests_sub': 'What matters to you? (pick 1 or 2)',
      'ps_style_sec': 'Learning style',
      'ps_style_sub': 'When an idea is hard, what helps you most?',
      'grade_5': 'Grade 5',
      'grade_6': 'Grade 6',
      'grade_7': 'Grade 7',
      'grade_8': 'Grade 8',
      'int_games': 'Games & challenges',
      'int_sports': 'Sports & motion',
      'int_art': 'Drawing & design',
      'int_science': 'Science & tech',
      'int_building': 'Building & architecture',
      'int_nature': 'Nature & energy',
      'int_helping': 'Helping people',
      'int_puzzles': 'Puzzles & thinking',
      'int_reading': 'Reading & stories',
      'style_step_title': 'Step by step',
      'style_step_desc': 'I prefer someone to lay out the idea for me first',
      'style_try_title': 'I try fast',
      'style_try_desc': 'Give me a short example and I will apply it myself',
      'style_story_title': 'A real-life story',
      'style_story_desc':
          'I want a real situation that shows the goal and the why',
      // theme selection
      'ts_appbar': 'Pick your passion color',
      'ts_confirm': 'Confirm theme and go',
      'theme_science_name': 'Science & technology',
      'theme_science_desc': 'For lovers of space, robots and AI 🌌',
      'theme_art_name': 'Art & creativity',
      'theme_art_desc': 'For story-makers and imaginative artists 🎨',
      'theme_sport_name': 'Sports & adventure',
      'theme_sport_desc':
          'For fans of physical challenges and constant action ⚽',
      'theme_games_name': 'Games & challenge',
      'theme_games_desc': 'For puzzle-solvers leveling up their knowledge 🎮',
      'ts_heading': 'Color your learning journey! 🎨',
      'ts_sub':
          'Pick the theme that reflects your energy and passion, and we will color the whole app to match your unique taste.',
      'ts_preview_label': 'A live preview of your new app:',
      'ts_choose': 'Pick your favorite passion to apply the colors:',
      'ts_pv_journey': 'My daily journey',
      'ts_pv_badge': 'Smart Explorer rank 🏆',
      'ts_pv_progress': 'Study progress level',
      'ts_quick_test': 'Start the quick test 🚀',
      // profile screen
      'profile_title': 'My profile',
      'profile_games_made': 'Games created',
      'profile_total_points': 'Total points',
      'profile_grade': 'Grade',
      'profile_language': 'Language',
      // about screen
      'about_appbar': 'About the adventure',
      'about_version': 'Enhanced beta v1.0.0 🚀',
      'about_why_title': 'Why openMind? 🤔',
      'about_why_body':
          'Because no student needs to be compared to others — they need to be understood as they are.\n\n'
          'Behind every student is a unique way of understanding, an interest that pulls them, and a talent waiting to find its place.\n\n'
          'In a world full of screens, games, fast content and endless options, students need a learning experience that engages them mindfully, helps them focus, and shows them where their path could be.\n\n'
          'We built openMind to turn learning from rigid memorization into an interactive experience close to the student: they learn, try, make mistakes, understand, then start to see their path more clearly.',
      'about_vision_title': 'Our vision ✨',
      'about_vision_body':
          'To make learning a safe, personal space that helps every student understand in their own way, discover what draws them, and connect what they learn to their life, reality and future.\n\n'
          'We believe knowledge is not just for memorizing but for understanding life and serving people — and that the strongest society is built not from identical people, but from people who each know their value and place.',
      'about_what_title': 'What does openMind do? 🚀',
      'about_feat1_title': 'Interactive challenges',
      'about_feat1_desc':
          'Turns lessons into engaging interactive challenges and experiences.',
      'about_feat2_title': 'Framing ideas smartly',
      'about_feat2_desc':
          'Brings each idea closer in the way that best fits the student\'s mind.',
      'about_feat3_title': 'Exploring interests',
      'about_feat3_desc':
          'Learns from the student\'s choices to reveal their interests and future leanings.',
      'about_feat4_title': 'Connecting to reality',
      'about_feat4_desc':
          'Shows how what they learn connects to real, practical life around them.',
      'about_feat5_title': 'Building self-worth',
      'about_feat5_desc':
          'Helps them feel they have a unique value, a clear path, and a place in society.',
      'about_footer':
          'Made with love for Syria\'s promising future generation ❤️',
      // login (cosmetic)
      'login_welcome': 'Welcome to the play & challenge journey! 👋',
      'login_sub': 'Ready to take on this exciting adventure?',
      'login_email': 'Email',
      'login_password': 'Password',
      'login_forgot': 'Forgot your password?',
      'login_go': 'Go now',
      'login_guest': 'Try as an explorer guest',
      'login_no_account': "Don't have an account? ",
      'login_create': 'Create one now',
      'login_note': 'Fully supports both Arabic and English interfaces.',
    },
    'ar': {
      'welcome': 'مرحباً بك في إيدوميند',
      'magic_start': 'البداية السحرية',
      'change_language': 'تغيير اللغة',
      'student_profile': 'ملف الطالب',
      'level 3': 'المستوى 3',
      // home (AI-game learning path)
      'level_label': 'المستوى',
      'points_label': 'نقطة',
      'create_game': 'أنشئ لعبة',
      'create_first_game': 'أنشئ لعبتك الأولى!',
      'tap_to_play': 'اضغط هنا!',
      'my_games': 'ألعابي',
      'demo_games': 'ألعاب تجريبية',
      'demo_games_short': 'تجريبي',
      'demo_games_sub': 'ألعاب عينة مدمجة يمكنك لعبها دون اتصال.',
      'best_score': 'الأفضل',
      'plays': 'مرات اللعب',
      'play': 'العب',
      'not_now': 'ليس الآن',
      'lets_play': 'انطلق لنلعب!',
      'stage_intro_body':
          'الهدهد والنحلة مستعدان لمساعدتك في "{title}" وجمع أحلى عسل معرفي! هل أنت جاهز للتحدي؟',
      'welcome_to': 'مرحباً بك في {title}',
      'offline_create_hint':
          'اتصل بخادم لإنشاء ألعاب جديدة. لا يزال بإمكانك إعادة لعب الألعاب المحفوظة دون اتصال.',
      // settings
      'settings': 'الإعدادات',
      'server_address': 'عنوان الخادم',
      'test_connection': 'اختبار الاتصال',
      'connection_ok': 'تم الاتصال! الخادم يعمل.',
      'connection_fail': 'تعذّر الوصول إلى الخادم.',
      'change_theme': 'تغيير السمة',
      'language': 'اللغة',
      'privacy_note':
          'تقليل البيانات: الاسم المستعار فقط — بدون بريد إلكتروني أو تتبّع.',
      'nav_home': 'الرئيسية',
      'nav_profile': 'ملفي',
      'nav_about': 'حول',
      'nav_settings': 'الإعدادات',
      'nav_learn': 'رحلات',
      // middle-school shell (grades 7-9)
      'nav_start': 'البداية',
      'nav_journey': 'رحلتي',
      'nav_tutor': 'مساعدي',
      'nav_me': 'أنا',
      'journey_title': 'رحلتي',
      'journey_subtitle':
          'خريطتك الحقيقية للصف السابع: ما أنجزته، وأين تقف الآن، وما الذي يُفتح بعده.',
      'journey_pick_sub':
          'اختر مسارك: كل مسار فكرة كبيرة من منهاجك تُروى عبر دروس حقيقية.',
      'journey_pick_path': 'اختر مسارك!',
      'journey_locked': 'مقفلة',
      'path_ready_progress': '{n} من {m} جاهزة',
      // honest grade gating (grades whose curriculum is not authored yet)
      'grade_word_7': 'الصف السابع',
      'grade_word_8': 'الصف الثامن',
      'grade_word_9': 'الصف التاسع',
      'grade_soon_title': 'منهاج {g} قيد الإعداد',
      'grade_soon_body':
          'نبني دروس صفك بالعناية نفسها التي بنينا بها دروس الصف السابع، ولن نعرض لك محتوى ليس لصفك.',
      'grade_soon_can': 'ما تستطيع فعله الآن',
      'grade_soon_ask': 'اسأل مساعدك عن أي درس',
      'start_greeting': 'أهلًا بعودتك،',
      'start_subtitle': 'خطوة واضحة واحدة في كل مرة — تابع من حيث توقفت.',
      'start_continue': 'تابع رحلتك',
      'start_begin': 'ابدأ رحلتك',
      'start_continue_cta': 'متابعة التعلم',
      'start_begin_cta': 'ابدأ التعلم',
      'start_all_done_title': 'أنجزت كل التجارب المفتوحة!',
      'start_all_done_body':
          'تجارب جديدة في الطريق. في هذه الأثناء يمكنك إعادة أي تجربة من رحلتك أو استكشاف فكرة مع مساعدك.',
      'start_open_journey': 'افتح رحلتي',
      'start_ask_title': 'اسأل مساعدك',
      'start_ask_sub': 'سؤال في أي شيء — تحصل على تلميح يقودك، لا جوابًا جاهزًا.',
      'start_now_label': 'لحظتك التعليمية الآن',
      'start_begin_exp': 'ابدأ التجربة',
      'start_resume_exp': 'تابع التجربة',
      'start_explore_next': 'استكشف المفهوم التالي',
      'start_exp_position': 'التجربة {n} من {m} في هذا المسار',
      'start_resume_step': 'توقفت عند الخطوة {n} من {m}',
      'journey_here': 'أنت هنا',
      'me_title': 'أنا',
      'me_stage_middle': 'المرحلة الإعدادية',
      'me_experiences_done': 'تجربة مكتملة',
      'me_paths_done': 'مسارات مكتملة',
      'me_advanced': 'خيارات متقدمة',
      // context lens (middle school)
      'ctx_sheet_title': 'عدستك في التعلم',
      'ctx_sheet_sub':
          'اختر العالم الذي تأتي منه أمثلتك. تغيّر العدسة الحكاية حول الفكرة — لا الفكرة نفسها ولا صعوبتها ولا تقدمك.',
      'ctx_chip_label': 'عدستي',
      'ctx_chip_pick': 'اختر عدسة التعلم',
      'ctx_none': 'بدون عدسة',
      'ctx_market': 'السوق والتجارة',
      'ctx_building': 'البناء والعمران',
      'ctx_water_energy': 'الماء والطاقة',
      'ctx_roads_transport': 'الطرق والمواصلات',
      'ctx_technology': 'التقنية',
      // learning engine (features/learn)
      'learn_title': 'رحلات التعلم',
      'learn_subtitle':
          'مواقف حقيقية من مدينتك وحيّك — تستكشف وتقرر وتكتشف الفكرة بنفسك.',
      'learn_grade': 'الصف',
      'learn_experiences': 'تجارب',
      'learn_start': 'ابدأ',
      'learn_replay': 'أعد التجربة',
      'learn_soon': 'قريبًا',
      'learn_continue': 'متابعة',
      'learn_finish': 'إنهاء',
      'learn_done_title': 'أنجزت المهمة!',
      'learn_done_body': 'اتخذت القرارات واكتشفت الفكرة بنفسك في',
      'learn_back_to_path': 'العودة إلى الرحلة',
      'learn_need_help': 'هل تحتاج مساعدة؟',
      // check step (تحقق من الفهم)
      'learn_check_item': 'سؤال {n} من {m}',
      'learn_check_next': 'التالي',
      'learn_check_score': 'أجبت صحيحًا عن {c} من {m}',
      'learn_check_review': 'راجع الفكرة مع مساعدك',
      // Ask OpenMind (tutor)
      'nav_ask': 'اسأل',
      'tutor_title': 'اسأل أوبن مايند',
      'tutor_subtitle': 'سؤال في أي مادة — أساعدك على التفكير خطوة بخطوة، لا أعطيك الجواب جاهزًا.',
      'tutor_welcome':
          'أهلًا! اسألني في الرياضيات أو العلوم أو العربية أو الإنكليزية أو أي شيء تتعلمه، وسأرافقك خطوة بخطوة.',
      'tutor_input_hint': 'اكتب سؤالك…',
      'tutor_thinking': 'أفكر…',
      'tutor_offline': 'اتصل بالخادم أولًا (من الإعدادات) حتى أستطيع الإجابة عن أسئلتك.',
      'tutor_error': 'حدث خطأ — جرّب مرة أخرى بعد قليل.',
      'tutor_rate_limited': 'أسئلة كثيرة في هذه الساعة! خذ استراحة قصيرة ثم عد.',
      'tutor_try_again': 'الآن جرّب بنفسك!',
      'tutor_help_title': 'مساعدة أوبن مايند',
      'tutor_type_explanation': 'شرح',
      'tutor_type_hint': 'تلميح',
      'tutor_type_question': 'سؤال',
      'tutor_type_encouragement': 'تشجيع',
      'tutor_type_correction': 'تصحيح',
      'tutor_type_next_step': 'الخطوة التالية',
      // tutor quick actions (middle school)
      'qa_simpler': 'اشرحها بطريقة أبسط',
      'qa_example_ctx': 'أعطني مثالًا من سياقي',
      'qa_ask_me': 'اسألني سؤالًا يساعدني أفهم',
      'qa_try_again': 'دعني أجرب مرة أخرى',
      'qa_hint_only': 'أعطني تلميحًا وليس الحل',
      // tutor interactive blocks (Ask → See → Try)
      'tutor_new_chat': 'محادثة جديدة',
      'blk_check': 'تحقق',
      'blk_your_value': 'قيمتك',
      'blk_correct': 'صحيح! أحسنت',
      'blk_partial': 'اقتربت — انظر إلى المواضع المعلَّمة',
      'blk_incorrect': 'ليست صحيحة بعد — سيتابع مساعدك من هنا',
      'blk_sent': 'أُرسلت نتيجتك إلى مساعدك',
      'blk_answered': 'أنجزت هذا النشاط — نتيجته عند مساعدك',
      'blk_item_of': 'العنصر {n} من {m}',
      'blk_pair_of': 'وصلت {n} من {m} أزواج',
      'ir_numberline': 'وضعت المؤشر عند {v} (الهدف {t})',
      'ir_order': 'ترتيبي: {list}',
      'ir_sort': 'صنفت {c} من {m} تصنيفًا صحيحًا',
      'ir_match': 'وصلت الأزواج الـ{m} كلها مع {c} محاولات خاطئة',
      // onboarding (5-step learner flow)
      'onb_title': 'أهلاً بك في OpenMind',
      'onb_subtitle': 'خلّينا نبدأ رحلة تعلّم تناسبك',
      'onb_cta': 'ابدأ',
      'onb_next': 'التالي',
      'onb_back': 'رجوع',
      'onb_step_of': 'الخطوة {n} من {m}',
      'onb_name_title': 'شو اسمك؟',
      'onb_name_sub': 'حتى نعرف كيف نناديك',
      'onb_name_hint': 'اكتب اسمك هنا',
      'onb_stage_title': 'بأي مرحلة تدرس؟',
      'onb_stage_sub': 'اختار مرحلتك وصفك',
      'onb_stage_primary': 'ابتدائي',
      'onb_stage_middle': 'إعدادي',
      'onb_grade_sem': 'الصف {g}',
      'onb_g1': 'الأول',
      'onb_g2': 'الثاني',
      'onb_g3': 'الثالث',
      'onb_g4': 'الرابع',
      'onb_g5': 'الخامس',
      'onb_g6': 'السادس',
      'onb_g7': 'السابع',
      'onb_g8': 'الثامن',
      'onb_g9': 'التاسع',
      'onb_interests_title': 'شو الأشياء اللي بتحبها؟',
      'onb_interests_sub': 'اختار شيئين',
      'onb_int_science': 'علوم واختراعات',
      'onb_int_tech': 'تقنية ومستقبل',
      'onb_int_sport': 'رياضة وحركة',
      'onb_int_art': 'رسم وتصميم',
      'onb_int_stories': 'قصص وتاريخ',
      'onb_int_nature': 'طبيعة وبيئة',
      'onb_count_of': '{n} من 2',
      'onb_style_title': 'كيف تحب نبدأ؟',
      'onb_style_sub': 'اختار الطريقة الأقرب إلك',
      'onb_style_step': 'اشرح لي خطوة بخطوة',
      'onb_style_try': 'خلّيني أجرّب',
      'onb_style_story': 'قصة ومغامرة',
      'onb_style_real': 'من موقف واقعي',
      'onb_accent_title': 'اختار لون مساحتك',
      'onb_color_blue': 'أزرق',
      'onb_color_green': 'أخضر',
      'onb_color_yellow': 'أصفر',
      'onb_color_teal': 'فيروزي',
      'onb_color_coral': 'مرجاني',
      'onb_color_orange': 'برتقالي',
      'onb_finish_cta': 'ابدأ رحلتي',
      'onb_done_hi': 'أهلاً {name}!',
      'onb_done_sub': 'رحلتك جاهزة',
      // profile setup
      'ps_appbar': 'جهّز تجربتك',
      'ps_name_q': 'ما اسمك؟',
      'ps_name_hint': 'اسمك',
      'ps_gender_q': 'أنت',
      'ps_male': 'ذكر',
      'ps_female': 'أنثى',
      'ps_class_q': 'في أي صف أنت؟',
      'ps_class_hint': 'اختر صفك',
      'ps_interests_q': 'ما الذي تحبه؟ (اختر اثنين كحد أقصى)',
      'ps_style_q': 'كيف تحب أن تتعلم؟',
      'ps_continue': 'تابع',
      'ps_max_interests': 'يمكنك اختيار اهتمامين فقط للحفاظ على تخصيص ذكي!',
      'ps_sub': 'اختيارات بسيطة تجعل EduMind أقرب لك',
      'ps_basic': 'المعلومات الأساسية',
      'ps_basic_sub': 'الاسم، الجنس والصف الدراسي العلمي',
      'ps_name_label': 'اسمك',
      'ps_name_hint2': 'اكتب اسمك هنا   ...',
      'ps_class_label': 'صفّك الدراسي',
      'ps_class_hint2': 'اختر المرحلة الدراسية الحالية',
      'ps_interests_sec': 'قسم الاهتمامات',
      'ps_interests_sub': 'ما الأشياء التي تهمك؟ (اختر 1 أو 2 فقط)',
      'ps_style_sec': 'قسم طريقة التعلم',
      'ps_style_sub': 'عندما تكون الفكرة صعبة، ما الذي يساعدك أكثر؟',
      'grade_5': 'الصف الخامس',
      'grade_6': 'الصف السادس',
      'grade_7': 'الصف السابع',
      'grade_8': 'الصف الثامن',
      'int_games': 'ألعاب وتحديات',
      'int_sports': 'رياضة وحركة',
      'int_art': 'رسم وتصميم',
      'int_science': 'علوم وتكنولوجيا',
      'int_building': 'بناء وعمارة',
      'int_nature': 'طبيعة وطاقة',
      'int_helping': 'مساعدة الناس',
      'int_puzzles': 'ألغاز وتفكير',
      'int_reading': 'قراءة وقصص',
      'style_step_title': 'خطوة بخطوة',
      'style_step_desc': 'أفضل أن يرتّب لي شخص ما الفكرة الموجهة مسبقاً',
      'style_try_title': 'أجرّب بسرعة',
      'style_try_desc': 'أعطني مثالاً قصيراً وسأقوم بالتطبيق فوراً بنفسي',
      'style_story_title': 'قصة من الحياة',
      'style_story_desc': 'أريد موقفاً واقعياً يجعلني أفهم الهدف والسبب',
      // theme selection
      'ts_appbar': 'اختر لون شغفك',
      'ts_confirm': 'تأكيد السمة والانطلاق',
      'theme_science_name': 'شغف العلوم والتكنولوجيا',
      'theme_science_desc': 'لعشاق الفضاء، الروبوتات والذكاء الاصطناعي 🌌',
      'theme_art_name': 'شغف الفن والإبداع',
      'theme_art_desc': 'لصناع القصص ورسامي الخيال اللامتناهي 🎨',
      'theme_sport_name': 'شغف الرياضة والمغامرة',
      'theme_sport_desc': 'لمحبي التحديات البدنية والنشاط الدائم ⚽',
      'theme_games_name': 'شغف الألعاب والتحدي',
      'theme_games_desc': 'لعشاق حل الألغاز وتجاوز مستويات المعرفة 🎮',
      'ts_heading': 'لوّن رحلتك التعليمية! 🎨',
      'ts_sub':
          'اختر السمة التي تعكس حماسك وشغفك، وسنقوم بتلوين كافة أقسام التطبيق لتناسب ذوقك الفريد.',
      'ts_preview_label': 'معاينة حية لتطبيقك الجديد:',
      'ts_choose': 'اختر شغفك المفضل لتطبيق الألوان:',
      'ts_pv_journey': 'رحلتي اليومية',
      'ts_pv_badge': 'لقب المكتشف الذكي 🏆',
      'ts_pv_progress': 'مستوى التقدم الدراسي',
      'ts_quick_test': 'ابدأ الاختبار السريع 🚀',
      // profile screen
      'profile_title': 'ملفي الشخصي',
      'profile_games_made': 'الألعاب المُنشأة',
      'profile_total_points': 'مجموع النقاط',
      'profile_grade': 'الصف',
      'profile_language': 'اللغة',
      // about screen
      'about_appbar': 'حول المغامرة',
      'about_version': 'النسخة التجريبية المطورّة v1.0.0 🚀',
      'about_why_title': 'لماذا openMind؟ 🤔',
      'about_why_body':
          'لأن كل طالب لا يحتاج أن يُقارن بغيره، بل أن يُفهم كما هو.\n\n'
          'وراء كل طالب طريقة خاصة في الفهم، واهتمام يشدّه، وموهبة تنتظر أن تجد مكانها.\n\n'
          'في عالم مليء بالشاشات، الألعاب، المحتوى السريع، وكثرة الخيارات، صار الطالب يحتاج تجربة تعلّم تشدّه بوعي، وتساعده يركّز، ويفهم أين يمكن أن يكون طريقه.\n\n'
          'صممنا openMind ليحوّل التعلّم من حفظ جامد إلى تجربة تفاعلية قريبة من الطالب؛ يتعلّم، يجرّب، يخطئ، يفهم، ثم يبدأ يرى طريقه بشكل أوضح.',
      'about_vision_title': 'رؤيتنا ✨',
      'about_vision_body':
          'أن نجعل التعلّم مساحة آمنة وشخصية، تساعد كل طالب على أن يفهم بطريقته، يكتشف ما يشدّه، ويربط ما يتعلّمه بحياته وواقعه ومستقبله.\n\n'
          'نؤمن أن العلم ليس للحفظ فقط، بل لفهم الحياة وخدمة الناس، وأن المجتمع الأقوى لا يُبنى من أشخاص متشابهين، بل من أشخاص يعرف كل واحد منهم قيمته ومكانه.',
      'about_what_title': 'ماذا يفعل openMind؟ 🚀',
      'about_feat1_title': 'التحديات التفاعلية',
      'about_feat1_desc': 'يحوّل الدروس إلى تحديات وتجارب تفاعلية مشوقة.',
      'about_feat2_title': 'تقريب الأفكار ذكياً',
      'about_feat2_desc': 'يقرّب الفكرة بالطريقة الأنسب والأقرب لذهن الطالب.',
      'about_feat3_title': 'استكشاف الاهتمامات',
      'about_feat3_desc':
          'يتعلّم من اختيارات الطالب ليكشف اهتماماته وميوله المستقبليّة.',
      'about_feat4_title': 'الربط بالواقع الحقيقي',
      'about_feat4_desc':
          'يريه كيف يرتبط ما يتعلّمه بالحياة الواقعية والعملية من حوله.',
      'about_feat5_title': 'بناء القيمة الذاتية',
      'about_feat5_desc':
          'يساعده أن يشعر أن له قيمة فريدة، وطريقاً واضحاً، ومكاناً في المجتمع.',
      'about_footer': 'صُنع بكل حب لجيل المستقبل السوري الواعد ❤️',
      // login (cosmetic)
      'login_welcome': 'أهلاً بك في رحلة اللعب والتحدي ! 👋',
      'login_sub': 'هل أنت مستعد لخوض هذه المغامرة الشيّقة ؟',
      'login_email': 'البريد الإلكتروني',
      'login_password': 'كلمة المرور',
      'login_forgot': 'هل نسيت كلمة السر؟',
      'login_go': 'انطلق الآن',
      'login_guest': 'جرب كـ ضيف استكشافي',
      'login_no_account': 'ليس لديك حساب؟ ',
      'login_create': 'أنشئ حساباً الآن',
      'login_note': 'يدعم واجهتي اللغة العربية والإنجليزية بالكامل.',
    },
  };

  // دالة لجلب النص بناءً على مفتاح الكلمة واللغة الحالية
  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }

  /// translate + simple {placeholder} substitution, e.g.
  /// translateWith('welcome_to', {'title': 'Math'}).
  String translateWith(String key, Map<String, String> params) {
    var s = translate(key);
    params.forEach((k, v) => s = s.replaceAll('{$k}', v));
    return s;
  }
}

// الـ Delegate الخاص بالترجمة
class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(LocalizationsDelegate<AppLocalizations> old) => false;
}
